
DROP TABLE PASSAGEIRO;
CREATE TABLE PASSAGEIRO(
CPF INT NOT NULL,
NOMEPASS VARCHAR(150) NOT NULL,
CODASSENTO INT NOT NULL
);

ALTER TABLE PASSAGEIRO
ADD CONSTRAINT FK_PASSAGEIROASSENTO FOREIGN KEY (CODASSENTO) REFERENCES ASSENTO(CODASSENTO);

ALTER TABLE PASSAGEIRO
ADD CONSTRAINT PK_PASSAGEIRO PRIMARY KEY(CPF);



DROP TABLE ASSENTO;
CREATE TABLE ASSENTO (
CODASSENTO INT NOT NULL,
NUMEROSERIAVIAO INT NOT NULL
);

ALTER TABLE ASSENTO
ADD CONSTRAINT FK_ASSENTOAVIAO FOREIGN KEY (NUMEROSERIAVIAO) REFERENCES AVIAO(NUMEROSERIAVIAO);

ALTER TABLE ASSENTO
ADD CONSTRAINT PK_ASSENTO PRIMARY KEY(CODASSENTO);

DROP TABLE AVIAO;
CREATE TABLE AVIAO(
NUMEROSERIAVIAO INT NOT NULL,
MODELOAVIAO VARCHAR(30) NOT NULL
);

ALTER TABLE AVIAO
ADD CONSTRAINT PK_AVIAO PRIMARY KEY(NUMEROSERIAVIAO);

DROP TABLE ECONOMICO;
CREATE TABLE ECONOMICO(
CODASSENTO INT NOT NULL,
CODECO INT NOT NULL
);
ALTER TABLE ECONOMICO
ADD CONSTRAINT PK_ECONOMICO PRIMARY KEY(CODECO);

ALTER TABLE ECONOMICO
ADD CONSTRAINT FK_ASSENTOECONOMICO FOREIGN KEY(CODASSENTO) REFERENCES ASSENTO(CODASSENTO);

DROP TABLE EXECUTIVO;
CREATE TABLE EXECUTIVO(
CODASSENTO INT NOT NULL,
CODEXE INT NOT NULL
);

ALTER TABLE EXECUTIVO
ADD CONSTRAINT FK_ASSENTOEXECUTIVO FOREIGN KEY(CODASSENTO) REFERENCES ASSENTO(CODASSENTO);

ALTER TABLE EXECUTIVO
ADD CONSTRAINT PK_EXECUTIVO PRIMARY KEY(CODEXE);
